config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
  has_many :messages


  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "グループを編集しました"
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      else
        @messages = @group.messages.includes(:user)
        flash.now[:alert] = 'メッセージを入力してください。'
        render :index
      end
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
    redirect_to root_path
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label "チャットメンバーを追加", class: "chat-group-form__label"
    .chat-group-form__field--right
      .chat-group-form__search
        = f.text_field :users , class: "chat-group-form__input", id: "user-search-field", placeholder: "追加したいユーザー名を入力してください", value: nil
    .chat-group-form__field--right
      #user-search-result

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      #user-search-add
        - @group.users.each do |user|
          .chat-group-user
            %input{name: "group[user_ids][]", type: "hidden", value: user.id}
            .chat-group-user__name
              =user.name
            - unless (user.name == current_user.name)
              .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

  .chat-group-form__field
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render "form" , {group: @group}

app/views/groups/index.html.haml
.side-bar
  = render "messages/side-bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render "form" , {group: @group}

app/views/layouts/_notification.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: "layouts/notification"
    = yield

app/views/messages/_message.html.haml
.message{data: {message: {id: message.id}}}
  .message__name
    = message.user.name
  .message__date
    = message.updated_at.strftime("%Y/%m/%d %H:%M")
  - if message.content.present?
    .message__text
      = message.content
  .message__image
    = image_tag message.image.url if message.image.present?

app/views/messages/_side-bar.html.haml
.user-bar
  .user-bar__name
    = current_user.name
  %li.user-bar__link
    =link_to new_group_path, class: "user-bar__link_icon" do
      %i.fa.fa-edit
    =link_to edit_user_registration_path, class: "user-bar__link_icon" do
      %i.fa.fa-cog
.group-lists
  - current_user.groups.each do |group|
    = link_to group_messages_path(group), class: "group-list__link" do
      .group-list
        .group-list__name
          = group.name
        .group-list__new-chat
          = group.show_last_message

app/views/messages/index.html.haml
.side-bar
  = render "side-bar"

.chat-main
  .main-header
    .main-header__group-name
      = @group.name
    .main-header__menber
      .main-header__menber_list Member：
      .main-header__menber_list
        - @group.users.each do |user|
          .main-header__menber_name
            = user.name
    .main-header__edit-button
      = link_to "Edit", edit_group_path(@group), class: "main-header__edit-button_link"
  .chat-main__chat-list
    = render @messages
  .chat-main__input-box
    .input
      = form_for [@group, @message] do |f|
        = f.text_field :content, class: "input__text", placeholder: "type a message"
        .input__image
          = f.label :image do
            = fa_icon "image", class: "input__image__icon"
            = f.file_field :image, class: "input__image__hiden"
        = f.submit "Send", class: "input__submit"